# Generated by Django 5.1.5 on 2025-01-28 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='preferences',
        ),
    ]
