# Generated by Django 5.1.5 on 2025-01-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_trip_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
