# Generated by Django 5.1.5 on 2025-01-30 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_city_district_hotel_touristspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.district'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'district')},
        ),
    ]
