# Generated by Django 5.1.5 on 2025-01-30 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_city_district_alter_city_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='longitude',
        ),
    ]
