# Generated by Django 5.1.5 on 2025-01-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_city_latitude_remove_city_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='district',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='wikidata_id',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='category',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
