# Generated by Django 5.1.5 on 2025-01-31 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='image_url',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.district'),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='entrance_fee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='image_urls',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
