# Generated by Django 5.1.5 on 2025-01-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_touristspot_image_url_touristspot_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
