# Generated by Django 5.1.5 on 2025-01-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_touristspot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='address',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
