# Generated by Django 5.1.5 on 2025-02-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_town_touristspot_city_touristspot_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='normalized_name',
            field=models.CharField(default='', editable=False, max_length=255, unique=True),
        ),
    ]
