# Generated by Django 5.1.5 on 2025-02-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_touristspot_town_delete_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
