# Generated by Django 5.1.5 on 2025-02-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_touristspot_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
