# Generated by Django 5.1.5 on 2025-02-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_touristspot_image_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('budget', models.IntegerField()),
                ('days', models.IntegerField()),
                ('people', models.IntegerField()),
                ('preferences', models.TextField(blank=True, null=True)),
                ('itinerary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
