# Generated by Django 5.1.5 on 2025-02-20 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_tripplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='afternoon',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='day_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripplan',
            name='estimated_cost',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripplan',
            name='lunch',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='morning',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='suggested_hotel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
