# Generated by Django 5.1.5 on 2025-02-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_tripplan_afternoon_tripplan_day_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='evening',
            field=models.TextField(default=''),
        ),
    ]
