# Generated by Django 5.1.5 on 2025-02-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_tripplan_evening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripplan',
            name='days',
        ),
        migrations.AddField(
            model_name='tripplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
