# Generated by Django 5.1.5 on 2025-02-21 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_tripplan_days_tripplan_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
