# Generated by Django 5.1.5 on 2025-02-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_tripplan_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('people', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferences', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.DeleteModel(
            name='TripPlan',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
