# Generated by Django 5.1.5 on 2025-03-22 03:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_plantrip_remove_trip_user_delete_tripplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantrip',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantrip',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
