# Generated by Django 5.1.5 on 2025-03-23 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_plantrip_end_time_plantrip_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='description',
            new_name='amenities',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='price_range',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.district'),
        ),
    ]
