# Generated by Django 5.1.5 on 2025-03-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_description_hotel_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='longitude',
        ),
    ]
