# Generated by Django 5.1.5 on 2025-04-09 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_hotel_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('morning', models.TextField()),
                ('afternoon', models.TextField()),
                ('evening', models.TextField()),
                ('lunch', models.CharField(max_length=255)),
                ('estimated_cost', models.CharField(max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='main.plantrip')),
            ],
        ),
    ]
