# Generated by Django 5.1.5 on 2025-04-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_savedtripplan_delete_dailyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='savedtripplan',
            name='selected_hotels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
