# Generated by Django 5.1.5 on 2025-04-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_profile_profile_pic_savedtripplan_selected_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtripplan',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
