# Generated by Django 5.1.5 on 2025-04-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_savedtripplan_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtripplan',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
