# Generated by Django 5.1.5 on 2025-05-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_profile_bio_profile_district_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
