# Generated by Django 5.1.5 on 2025-05-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
